### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [opensource-cards/translations#18]
Hi, I would be interested in collaborating with this project, are there still things to be translated into Spanish? Where can I find the files that need translation?

**Comment by rtkhanas** [comment]
Hi @dbucci24 thank you for being interested in this!

Spanish translations were deployed to https://andcards.com/ yesterday, if browse through the web site and find something weird, please, feel free to send a PR.

**Comment by dbucci24** [comment]
Hi @rtkhanas 

Do you mean that the translation is already finished?

**Comment by Rybachello** [comment]
Hi @dbucci24 ,
No really, there are couple phrases that need to be translated. I will add below the folder names with untranslated files.

**Comment by dbucci24** [comment]
That would be great! I wait for the name of the folders :)

**Comment by Rybachello** [comment]
@dbucci24 Hi! I created issuse #20 - it is a list of all folders in which translation is missing. Thank you for helping us!

**Comment by Rybachello** [comment]
Hi @vacilagodzila! Thank you again for helping us with translation into Spanish. We still improving our product and with that, there are new phases that need to be maintained. Can you help again with translation?

**Comment by vacilagodzila** [comment]
Hi, @Rybachello , I'll be on it in a few days, hope this is ok. Thank you for reaching out and letting me know!

**Comment by Rybachello** [comment]
@vacilagodzila Thank you for helping, I hope it will not take too much for you ;)
