### ISSUE TITLE
Translation progress

### ISSUE THREAD

**Issue by Rybachello** [opensource-cards/translations#20]
Folders: 
- [x] cards-marketing-blogs
- [x] cards-alert-confirmation-organization-user-delete
- [x] cards-page-event-create
- [x] cards-page-event-event-details
- [x] cards-page-event-main
- [x] cards-page-group-create
- [x] cards-page-group-main
- [x] cards-page-group-settings
- [x] cards-page-organization-announcement-create
- [x] cards-page-organization-announcements
- [x] cards-page-organization-booking-create
- [x] cards-page-organization-booking-details
- [x] cards-page-organization-booking-settings
- [x] cards-page-organization-card-validation
- [x] cards-page-organization-event-details
- [x] cards-page-organization-event-main
- [x] cards-page-organization-events-main
- [x] cards-page-organization-empty
- [x] cards-page-organization-membership-settings
- [x] cards-page-organization-guild-everyone-main
- [x] cards-page-organization-guild-main
- [x] cards-page-organization-join
- [x] cards-page-organization-invite
- [x] cards-page-organization-main
- [x] cards-page-organization-polls
- [x] cards-page-organization-properties
- [x] cards-page-organization-properties-details
- [x] cards-page-organization-properties-edit
- [x] cards-page-organization-requests-create
- [x] cards-page-organization-requests
- [x] cards-page-organizations-settings
- [x] cards-page-received-cards-main
- [x] cards-page-settings-main

**Comment by dzhebyan** [comment]
Completed the list and all other translations. Except marketing.
