### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by vacilagodzila** [opensource-cards/translations#6]
Hello, I'm interested in contributing for this repo with spanish translations. How can I start?

**Comment by rtkhanas** [comment]
Hello, @vacilagodzila thank you a lot for being interested in making Spanish translations.

This repo contains the translations for a [Cards Corp. marketing](https://andcards.com) web site (translations are located in folders with a `cards-marketing-` prefix) and the [andCards app](https://andcards.com/login), which you can access once you logging in.

I just added a short description how to add a new language, in your case - Spanish. It is located [here](https://github.com/opensource-cards/translations/blob/master/CONTRIBUTING.md).

We would be very happy and thankful for this help.

**Comment by vacilagodzila** [comment]
Great! I'll get to work on it later in the evening.

**Comment by vacilagodzila** [comment]
Hey, @rtkhanas , should "Republic of Korea" in "3F, 109 Cheongpa-ro,\n Yongsan-gu,\n Seoul 04370,\n Republic of Korea" remain untranslated?

**Comment by vacilagodzila** [comment]
Oh, I see. It's an address. Then **"republic of korea"** shall be translated. Got it.

**Comment by vacilagodzila** [comment]
Hey, @rtkhanas , is the `cards-page-` prefix also up for translation?

**Comment by rtkhanas** [comment]
Hey, @vacilagodzila , yes, basically all the folders here are up for the translation. The ‘cards-page-‘ prefix is used for pages in the andCards application.
